name: Flutter CI

on:
  push:
    paths:
      - 'flutter-app/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    paths:
      - 'flutter-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Pub get
        working-directory: flutter-app
        run: flutter pub get
      - name: Analyze
        working-directory: flutter-app
        run: flutter analyze
      - name: Debug build (APK)
        working-directory: flutter-app
        run: flutter build apk --debug
